title: Pedagogisk Mappe
email: edvard.pedersen@uit.no
description: >- # this means to ignore newlines until "baseurl:"
        Akademisk CV, pedagogisk mappe
github_username: edvardpedersen
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Edvard Pedersen"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Førstelektor ved UiT - Norges Arktiske Universitet."
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/edvardpedersen"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/edvard-pedersen"
    - label: "UiT"
      icon: "/assets/images/uit_logo.png"
      url: "https://uit.no/ansatte/person?p_document_id=588234"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/edvardpedersen"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/edvard-pedersen"
    - label: "UiT"
      icon: "/assets/images/uit_logo.png"
      url: "https://uit.no/ansatte/person?p_document_id=588234"

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

